environment:
  matrix:
    - nodejs_version: LTS
      configuration: publish

install:
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ./build.cmd

test: off

artifacts:
  - path: dist/
    name: dist