environment:
  matrix:
    - nodejs_version: STABLE
      configuration: publish
    - nodejs_version: LTS

install:
  - npm install -g npm
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - npm --version
  - node --version
  - npm --version

build_script:
  - ./build.cmd

test: off

artifacts:
  - path: dist/
    name: dist
